// Package database is the Postgres layer: connection setup, schema
// migrations (goose), and queries (hand-written here, or generated by sqlc
// into the sqlc subpackage).
package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"strconv"
	"time"

	_ "github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"

	sqlcdb "choccobear.tech/deedee/database/sqlc"
)

type Db struct {
	session *sql.DB
	queries *sqlcdb.Queries
}

type editEntry struct {
	Content   string    `json:"content"`
	ChangedAt time.Time `json:"changed_at"`
}

func Setup() (*Db, error) {
	host := os.Getenv("DATABASE_HOST")
	port := os.Getenv("DATABASE_PORT")
	user := os.Getenv("DATABASE_USER")
	pass := os.Getenv("DATABASE_PASS")
	dbName := os.Getenv("DATABASE_DB")

	psqlInfo := fmt.Sprintf("host=%s port=%s user=%s "+
		"password=%s dbname=%s sslmode=disable",
		host, port, user, pass, dbName)

	session, err := sql.Open("postgres", psqlInfo)
	if err != nil {
		return nil, fmt.Errorf("opening database: %w", err)
	}

	if err := session.Ping(); err != nil {
		return nil, fmt.Errorf("pinging database: %w", err)
	}
	slog.Info("database connected", "stats", session.Stats())

	if err := HandleMigrations(session); err != nil {
		return nil, fmt.Errorf("running migrations: %w", err)
	}

	return &Db{session: session, queries: sqlcdb.New(session)}, nil
}

// Ping reports whether the database is reachable, for use as a health check.
func (d *Db) Ping() error {
	return d.session.Ping()
}

// Close releases the underlying connection pool.
func (d *Db) Close() error {
	return d.session.Close()
}

func (d *Db) SaveUser(discordID string, username string) (int32, error) {
	id, err := strconv.ParseInt(discordID, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("invalid discord ID %s: %w", discordID, err)
	}
	return d.queries.SaveUser(context.Background(), sqlcdb.SaveUserParams{
		DiscordID:   id,
		DiscordUser: username,
	})
}

func (d *Db) SaveMessage(discordMessageID, channelID string, authorID int32, content string, createdAt time.Time) (int32, error) {
	return d.queries.SaveMessage(context.Background(), sqlcdb.SaveMessageParams{
		DiscordMessageID: discordMessageID,
		ChannelID:        channelID,
		AuthorID:         authorID,
		Content:          content,
		CreatedAt:        sql.NullTime{Time: createdAt, Valid: !createdAt.IsZero()},
	})
}

func (d *Db) GetMessageWithAuthor(discordMessageID string) (content, username, channelID string, createdAt time.Time, err error) {
	msg, err := d.queries.GetMessageWithAuthor(context.Background(), discordMessageID)
	if err != nil {
		return
	}
	content = msg.Content
	username = msg.DiscordUser
	channelID = msg.ChannelID
	if msg.CreatedAt.Valid {
		createdAt = msg.CreatedAt.Time
	}
	return
}

func (d *Db) SaveReaction(messageID, reactorID int32, emoji string) error {
	return d.queries.SaveReaction(context.Background(), sqlcdb.SaveReactionParams{
		MessageID: messageID,
		Emoji:     emoji,
		ReactorID: reactorID,
	})
}

func (d *Db) UpdateMessageContent(messageID string, newMessage string) error {
	ctx := context.Background()

	msg, err := d.queries.GetMessageForEdit(ctx, messageID)
	if err != nil {
		if err == sql.ErrNoRows {
			return fmt.Errorf("message not found")
		}
		return err
	}

	var history []editEntry
	if msg.EditHistory.Valid {
		if err := json.Unmarshal(msg.EditHistory.RawMessage, &history); err != nil {
			return fmt.Errorf("failed to parse edit_history: %w", err)
		}
	}

	history = append(history, editEntry{Content: msg.Content, ChangedAt: time.Now()})

	historyJSON, err := json.Marshal(history)
	if err != nil {
		return fmt.Errorf("failed to marshal edit_history: %w", err)
	}

	return d.queries.UpdateMessageContent(ctx, sqlcdb.UpdateMessageContentParams{
		Content:     newMessage,
		EditHistory: pqtype.NullRawMessage{RawMessage: historyJSON, Valid: true},
		ID:          msg.ID,
	})
}

func (d *Db) IsChannelCompleted(channelID string) (bool, error) {
	var id int
	sqlQuery := "SELECT id FROM completed_channels WHERE channel_id = $1"
	err := d.session.QueryRow(sqlQuery, channelID).Scan(&id)
	switch err {
	case sql.ErrNoRows:
		return false, nil
	case nil:
		return true, nil
	default:
		return false, err
	}
}

func (d *Db) SaveChannelName(channelID string, channelName string) error {
	sqlQuery := `INSERT INTO channel_name (name, discord_id)
VALUES ($1, $2)
ON CONFLICT (discord_id) DO UPDATE SET discord_id = EXCLUDED.discord_id;`

	_, err := d.session.Exec(sqlQuery, channelName, channelID)
	if err != nil {
		return fmt.Errorf("saving channel name for %s: %w", channelID, err)
	}
	return nil
}

func (d *Db) MarkChannelCompleted(channelID string) error {
	sqlQuery := `INSERT INTO completed_channels (channel_id, completed_at)
VALUES ($1, $2)
ON CONFLICT (channel_id) DO UPDATE SET completed_at = EXCLUDED.completed_at;`

	_, err := d.session.Exec(sqlQuery, channelID, time.Now())
	return err
}
