// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlcdb

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const getMessageForEdit = `-- name: GetMessageForEdit :one
SELECT id, edit_history, content, discord_message_id
FROM messages
WHERE discord_message_id = $1
`

type GetMessageForEditRow struct {
	ID               int32
	EditHistory      pqtype.NullRawMessage
	Content          string
	DiscordMessageID string
}

func (q *Queries) GetMessageForEdit(ctx context.Context, discordMessageID string) (GetMessageForEditRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageForEdit, discordMessageID)
	var i GetMessageForEditRow
	err := row.Scan(
		&i.ID,
		&i.EditHistory,
		&i.Content,
		&i.DiscordMessageID,
	)
	return i, err
}

const getMessageWithAuthor = `-- name: GetMessageWithAuthor :one
SELECT
    m.id,
    m.discord_message_id,
    m.channel_id,
    m.content,
    m.created_at,
    m.edit_history,
    u.discord_id,
    u.discord_user
FROM messages m
JOIN users u ON m.author_id = u.id
WHERE m.discord_message_id = $1
`

type GetMessageWithAuthorRow struct {
	ID               int32
	DiscordMessageID string
	ChannelID        string
	Content          string
	CreatedAt        sql.NullTime
	EditHistory      pqtype.NullRawMessage
	DiscordID        int64
	DiscordUser      string
}

func (q *Queries) GetMessageWithAuthor(ctx context.Context, discordMessageID string) (GetMessageWithAuthorRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageWithAuthor, discordMessageID)
	var i GetMessageWithAuthorRow
	err := row.Scan(
		&i.ID,
		&i.DiscordMessageID,
		&i.ChannelID,
		&i.Content,
		&i.CreatedAt,
		&i.EditHistory,
		&i.DiscordID,
		&i.DiscordUser,
	)
	return i, err
}

const saveMessage = `-- name: SaveMessage :one
INSERT INTO messages (discord_message_id, channel_id, author_id, content, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (discord_message_id) DO UPDATE
    SET channel_id  = EXCLUDED.channel_id,
        author_id   = EXCLUDED.author_id,
        content     = EXCLUDED.content,
        created_at  = EXCLUDED.created_at
RETURNING id
`

type SaveMessageParams struct {
	DiscordMessageID string
	ChannelID        string
	AuthorID         int32
	Content          string
	CreatedAt        sql.NullTime
}

func (q *Queries) SaveMessage(ctx context.Context, arg SaveMessageParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, saveMessage,
		arg.DiscordMessageID,
		arg.ChannelID,
		arg.AuthorID,
		arg.Content,
		arg.CreatedAt,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateMessageContent = `-- name: UpdateMessageContent :exec
UPDATE messages
SET content      = $1,
    edit_history = $2
WHERE id = $3
`

type UpdateMessageContentParams struct {
	Content     string
	EditHistory pqtype.NullRawMessage
	ID          int32
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageContent, arg.Content, arg.EditHistory, arg.ID)
	return err
}
