// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type ChannelName struct {
	ID        int32
	Name      string
	DiscordID string
}

type CompletedChannel struct {
	ID          int32
	ChannelID   string
	CompletedAt time.Time
}

type Message struct {
	ID               int32
	DiscordMessageID string
	ChannelID        string
	AuthorID         int32
	CreatedAt        sql.NullTime
	Content          string
	EditHistory      pqtype.NullRawMessage
}

type Reaction struct {
	ID        int32
	MessageID int32
	Emoji     string
	ReactorID int32
}

type Reminder struct {
	ID               int32
	Title            string
	AdditionalInfo   sql.NullString
	UserCreated      int64
	UsersToTag       []int64
	ReminderDatetime time.Time
}

type Todo struct {
	ID               int32
	ChannelMessageID string
	Title            string
	Description      sql.NullString
	Completed        interface{}
	CompletedBy      int64
}

type User struct {
	ID          int32
	DiscordID   int64
	DiscordUser string
}
