// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reactions.sql

package sqlcdb

import (
	"context"
)

const getReactionsByMessage = `-- name: GetReactionsByMessage :many
SELECT
    r.id,
    r.emoji,
    u.discord_user
FROM reactions r
JOIN users u ON r.reactor_id = u.id
WHERE r.message_id = $1
`

type GetReactionsByMessageRow struct {
	ID          int32
	Emoji       string
	DiscordUser string
}

func (q *Queries) GetReactionsByMessage(ctx context.Context, messageID int32) ([]GetReactionsByMessageRow, error) {
	rows, err := q.db.QueryContext(ctx, getReactionsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReactionsByMessageRow
	for rows.Next() {
		var i GetReactionsByMessageRow
		if err := rows.Scan(&i.ID, &i.Emoji, &i.DiscordUser); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveReaction = `-- name: SaveReaction :exec
INSERT INTO reactions (message_id, emoji, reactor_id)
VALUES ($1, $2, $3)
ON CONFLICT (message_id, emoji, reactor_id) DO UPDATE
    SET emoji      = EXCLUDED.emoji,
        reactor_id = EXCLUDED.reactor_id
`

type SaveReactionParams struct {
	MessageID int32
	Emoji     string
	ReactorID int32
}

func (q *Queries) SaveReaction(ctx context.Context, arg SaveReactionParams) error {
	_, err := q.db.ExecContext(ctx, saveReaction, arg.MessageID, arg.Emoji, arg.ReactorID)
	return err
}
