// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcdb

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, discord_id, discord_user
FROM users
WHERE discord_id = $1
`

func (q *Queries) GetUser(ctx context.Context, discordID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, discordID)
	var i User
	err := row.Scan(&i.ID, &i.DiscordID, &i.DiscordUser)
	return i, err
}

const saveUser = `-- name: SaveUser :one
INSERT INTO users (discord_id, discord_user)
VALUES ($1, $2)
ON CONFLICT (discord_id) DO UPDATE
    SET discord_user = EXCLUDED.discord_user
RETURNING id
`

type SaveUserParams struct {
	DiscordID   int64
	DiscordUser string
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, saveUser, arg.DiscordID, arg.DiscordUser)
	var id int32
	err := row.Scan(&id)
	return id, err
}
